#!/usr/bin/env python3
"""
scripts/generate.py — KnowledgeBase Agent Generator
----------------------------------------------------
Run this script once after cloning, or whenever you add/remove knowledge folders.

What it does (in order):
  1.  Loads env vars (.env or system environment)
  2.  Discovers top-level knowledge folders under KB_ROOT
  3.  Cleans up stale vector index files for removed folders
  4.  Builds / updates vector indexes for each folder
  5.  Generates (or updates) domain descriptions + keywords via LLM
      (soft-skipped if LLM is unreachable — uses folder name as placeholder)
  6.  Writes agents/vector_store/domain_meta.json
      (orchestrator reads this at runtime — no per-domain .py files needed)
  7.  Writes requirements.txt
  8.  Writes agents/SKILL.md and auto-copies to ~/.bob/skills/ if Bob is installed

Usage:
  python3 scripts/generate.py            # incremental (skip unchanged folders)
  python3 scripts/generate.py --force    # regenerate everything from scratch
  python3 scripts/generate.py --no-llm   # skip LLM steps (index + file gen only)
"""

import os
import re
import sys
import json
import shutil
import pathlib
import textwrap
import argparse
import datetime

# ── Environment loader ────────────────────────────────────────────────────────

def load_env(root: pathlib.Path):
    env_file = root / ".env"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip())

# ── Config resolution ─────────────────────────────────────────────────────────

# scripts/ lives one level below the repo root — resolve upward so all
# relative paths (agents/, .env, requirements.txt, etc.) stay correct.
SCRIPT_DIR = pathlib.Path(__file__).parent.parent.resolve()

# Make agents/ importable at module level (needed for _find_readme and other
# shared helpers).  Must come before any `from agent_base import …` statement.
sys.path.insert(0, str(SCRIPT_DIR / "agents"))
from agent_base import (  # noqa: E402
    _find_readme,
    DEFAULT_BLOCKLIST,
    INCLUDE_EXTS,
    SKIP_PATTERNS,
)

def resolve_kb_root() -> pathlib.Path:
    raw = os.environ.get("KB_ROOT", "")
    return pathlib.Path(raw).resolve() if raw else SCRIPT_DIR

def get_blocklist() -> set[str]:
    extra = os.environ.get("KB_IGNORE_FOLDERS", "")
    user  = {f.strip().lower() for f in extra.split(",") if f.strip()}
    return DEFAULT_BLOCKLIST | user

# ── Helpers ───────────────────────────────────────────────────────────────────

def should_skip(path: pathlib.Path) -> bool:
    return any(p in path.name.lower() for p in SKIP_PATTERNS)


def folder_to_safe_name(name: str) -> str:
    """ACE Docs → ace_docs  |  My Sales & Revenue → my_sales_revenue"""
    n = name.lower()
    n = re.sub(r"[^a-z0-9]+", "_", n)
    n = n.strip("_")
    return n


def agent_filename(folder_name: str) -> str:
    return f"agent_{folder_to_safe_name(folder_name)}.py"


def discover_folders(kb_root: pathlib.Path, blocklist: set[str]) -> list[str]:
    """Return top-level folder names that contain at least one indexable file."""
    folders = []
    for p in sorted(kb_root.iterdir()):
        if not p.is_dir():
            continue
        name_lower = p.name.lower()
        if name_lower in blocklist:
            continue
        # Exclude Python packaging artifacts — .egg-info and .dist-info directories
        # are generated by pip/setuptools and must never become knowledge domains.
        if name_lower.endswith(".egg-info") or name_lower.endswith(".dist-info"):
            continue
        has_files = any(
            f.suffix.lower() in INCLUDE_EXTS
            for f in p.rglob("*")
            if f.is_file() and not should_skip(f)
        )
        if has_files:
            folders.append(p.name)
    return folders


def count_files(folder: pathlib.Path) -> int:
    return sum(
        1 for f in folder.rglob("*")
        if f.is_file()
        and f.suffix.lower() in INCLUDE_EXTS
        and not should_skip(f)
    )


# ── LLM helpers ───────────────────────────────────────────────────────────────

def llm_available() -> bool:
    """Quick check — try to reach the LLM endpoint."""
    try:
        import httpx
        provider    = os.environ.get("KB_LLM_PROVIDER", "ollama").lower()
        base_url    = os.environ.get("KB_LLM_BASE_URL", "http://localhost:11434")
        if provider == "ollama":
            r = httpx.get(f"{base_url}/api/tags", timeout=5.0)
        else:
            # For OpenAI-compat just check the base URL is reachable
            r = httpx.get(base_url.rstrip("/"), timeout=5.0)
        return r.status_code < 500
    except Exception:
        return False


def call_llm_generate(prompt: str) -> str:
    """Call the LLM with a plain prompt and return text."""
    import httpx

    provider  = os.environ.get("KB_LLM_PROVIDER", "ollama").lower()
    base_url  = os.environ.get("KB_LLM_BASE_URL", "http://localhost:11434")
    model     = os.environ.get("KB_MODEL", "qwen3:14b")
    api_key   = os.environ.get("KB_API_KEY", "")
    messages  = [{"role": "user", "content": prompt}]

    if provider == "anthropic":
        headers = {
            "x-api-key":         api_key,
            "anthropic-version": "2023-06-01",
            "Content-Type":      "application/json",
        }
        r = httpx.post(
            f"{base_url}/v1/messages",
            headers=headers,
            json={"model": model, "max_tokens": 1024,
                  "temperature": 0.3, "messages": messages},
            timeout=60.0,
        )
        r.raise_for_status()
        return r.json()["content"][0]["text"].strip()

    if provider in ("openai", "custom"):
        b = base_url.rstrip("/")
        if "11434" in b and not b.endswith("/v1"):
            b = f"{b}/v1"
        headers = {"Content-Type": "application/json"}
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
        r = httpx.post(
            f"{b}/chat/completions",
            headers=headers,
            json={"model": model, "messages": messages, "temperature": 0.3},
            timeout=60.0,
        )
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"].strip()

    # Ollama
    import importlib as _imp
    _agents_dir = pathlib.Path(__file__).parent.parent / "agents"
    if str(_agents_dir) not in sys.path:
        sys.path.insert(0, str(_agents_dir))
    _cb = _imp.import_module("context_budget")
    r = httpx.post(
        f"{base_url}/api/chat",
        json={"model": model, "messages": messages, "stream": False,
              "options": {"temperature": 0.3, "num_ctx": _cb.get("num_ctx")}, "think": False},
        timeout=60.0,
    )
    r.raise_for_status()
    return r.json()["message"]["content"].strip()


# ── Domain meta generation ────────────────────────────────────────────────────

def generate_domain_meta(folder_name: str, folder: pathlib.Path) -> dict:
    """
    Ask the LLM to generate a description and keywords for this folder
    by sampling a few filenames + snippets.
    Returns { "description": str, "keywords": [str, ...] }
    """
    # Collect up to 20 file names + first-line snippets
    samples = []
    for f in sorted(folder.rglob("*")):
        if not f.is_file() or f.suffix.lower() not in INCLUDE_EXTS:
            continue
        if should_skip(f):
            continue
        try:
            if f.suffix.lower() in {".txt", ".md", ".csv"}:
                first_line = f.read_text(encoding="utf-8", errors="ignore")[:200]
            else:
                first_line = f"[{f.suffix.upper().lstrip('.')} file]"
            samples.append(f"- {f.name}: {first_line[:100]}")
        except Exception:
            samples.append(f"- {f.name}")
        if len(samples) >= 20:
            break

    samples_text = "\n".join(samples)

    prompt = f"""You are helping configure a knowledge base search system.
I have a folder called "{folder_name}" containing these files:

{samples_text}

Based on these files, respond with ONLY a valid JSON object in this exact format:
{{
  "description": "One sentence describing what this folder contains (max 200 chars)",
  "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5", "keyword6", "keyword7", "keyword8", "keyword9", "keyword10"]
}}

Rules:
- description: plain English, no quotes inside, max 200 characters
- keywords: 10-15 short words or phrases a user might type when asking about this domain
- respond with ONLY the JSON object, no explanation"""

    raw = call_llm_generate(prompt)

    # Extract JSON from response (LLM may wrap it in markdown)
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        try:
            data = json.loads(match.group())
            return {
                "description": str(data.get("description", folder_name))[:200],
                "keywords":    [str(k) for k in data.get("keywords", [])[:15]],
            }
        except json.JSONDecodeError:
            pass

    # Fallback
    return {"description": folder_name, "keywords": [folder_name.lower()]}


# ── Per-file summary generator ────────────────────────────────────────────────

def _extract_snippet_for_summary(file_path: pathlib.Path, max_chars: int = 2000) -> str:
    """
    Extract a representative text snippet from a file to feed to the summariser.
    Reuses the same lightweight extraction logic as embeddings.py.
    """
    ext = file_path.suffix.lower()
    try:
        if ext in {".txt", ".md", ".csv"}:
            return file_path.read_text(encoding="utf-8", errors="ignore")[:max_chars]

        elif ext == ".docx":
            import zipfile
            with zipfile.ZipFile(file_path) as z:
                with z.open("word/document.xml") as f:
                    xml = f.read().decode("utf-8", errors="ignore")
            text = re.sub(r"<[^>]+>", " ", xml)
            return " ".join(text.split())[:max_chars]

        elif ext == ".pdf":
            try:
                from pypdf import PdfReader
                reader = PdfReader(str(file_path))
                text = ""
                for page in reader.pages[:4]:
                    text += (page.extract_text() or "") + "\n"
                    if len(text) >= max_chars:
                        break
                return text[:max_chars]
            except Exception:
                return f"[PDF: {file_path.name}]"

        elif ext in {".pptx", ".ppt"}:
            try:
                from pptx import Presentation
                prs = Presentation(str(file_path))
                text = ""
                for slide in prs.slides[:6]:
                    for shape in slide.shapes:
                        if hasattr(shape, "text") and shape.text.strip():
                            text += shape.text.strip() + "\n"
                    if len(text) >= max_chars:
                        break
                return text[:max_chars]
            except Exception:
                return f"[PPTX: {file_path.name}]"

        elif ext in {".xlsx", ".xls"}:
            try:
                # Large XLSX files (>50 MB) must use the streaming aggregator —
                # openpyxl takes 80+ seconds to load a 160 MB file and only reads
                # the first 40 rows, producing a generic header dump.  The streaming
                # aggregator uses raw XML iterparse, reads all rows in one pass, and
                # returns a structured revenue/data summary with actual totals.
                MAX_XLSX_BYTES = 50 * 1024 * 1024  # 50 MB
                if file_path.stat().st_size > MAX_XLSX_BYTES:
                    _agents_dir = pathlib.Path(__file__).parent.parent / "agents"
                    if str(_agents_dir) not in sys.path:
                        sys.path.insert(0, str(_agents_dir))
                    from agent_base import _stream_xlsx_aggregate
                    return _stream_xlsx_aggregate(file_path, max_chars)

                import openpyxl
                wb = openpyxl.load_workbook(str(file_path), read_only=True, data_only=True)
                text = ""
                for sheet in wb.worksheets[:2]:
                    text += f"[Sheet: {sheet.title}]\n"
                    for row in sheet.iter_rows(max_row=40, values_only=True):
                        row_text = " | ".join(str(c) for c in row if c is not None)
                        if row_text.strip():
                            text += row_text + "\n"
                    if len(text) >= max_chars:
                        break
                return text[:max_chars]
            except Exception:
                return f"[XLSX: {file_path.name}]"

        elif ext == ".boxnote":
            try:
                data = json.loads(file_path.read_text(encoding="utf-8", errors="ignore"))
                def walk(node):
                    if isinstance(node, dict):
                        if node.get("type") == "text":
                            yield node.get("text", "")
                        for v in node.values():
                            yield from walk(v)
                    elif isinstance(node, list):
                        for item in node:
                            yield from walk(item)
                return " ".join(walk(data))[:max_chars]
            except Exception:
                return f"[BoxNote: {file_path.name}]"

    except Exception as e:
        return f"[Read error: {e}]"

    return f"[Unsupported: {file_path.name}]"


def generate_file_summary(file_name: str, snippet: str) -> str:
    """
    Ask the LLM to produce a 3–5 sentence summary of a single file.
    Returns the summary string (falls back to a truncated snippet on failure).
    """
    prompt = (
        f'Summarise the following content from a file called "{file_name}" '
        f"in 3 to 5 concise sentences. Focus on: what the file is about, "
        f"the key topics or data it contains, and who would find it useful. "
        f"Do NOT include phrases like 'This file contains' or 'This document is about'. "
        f"Write in plain prose. No bullet points. No markdown.\n\n"
        f"Content:\n{snippet}"
    )
    try:
        return call_llm_generate(prompt).strip()
    except Exception:
        # Graceful fallback: use first 300 chars of the snippet as the summary
        return snippet[:300].strip()


def build_file_summaries(
    folder_name: str,
    folder: pathlib.Path,
    kb_root: pathlib.Path,
    existing_cache: dict,
    force: bool = False,
) -> dict:
    """
    Generate 3–5 sentence LLM summaries for every indexable file in a folder.

    Uses a content-hash cache (agents/vector_store/file_summaries.json) so the
    LLM is only called for new or changed files.  Unchanged files are returned
    directly from cache.

    Args:
        folder_name:    KB domain folder name (e.g. "BizOps")
        folder:         Absolute path to the domain folder
        kb_root:        KB root path (for computing relative cache keys)
        existing_cache: Current contents of file_summaries.json (mutated in place)
        force:          If True, regenerate all summaries regardless of cache

    Returns:
        Dict mapping "FolderName/file.ext" → { "summary": str, "hash": str }
        (Only entries belonging to this folder — caller merges into full cache.)
    """
    import hashlib

    files = [
        f for f in sorted(folder.rglob("*"))
        if f.is_file()
        and f.suffix.lower() in INCLUDE_EXTS
        and not should_skip(f)
    ]

    folder_summaries: dict[str, dict] = {}
    new_count = 0
    total = len(files)

    for idx, f in enumerate(files, start=1):
        rel_key = str(f.relative_to(kb_root)).replace("\\", "/")
        try:
            file_hash = hashlib.md5(f.read_bytes()).hexdigest()
        except Exception:
            continue

        cached = existing_cache.get(rel_key, {})
        if not force and cached.get("hash") == file_hash and cached.get("summary"):
            # Cache hit — reuse without calling the LLM
            folder_summaries[rel_key] = cached
            continue

        # Cache miss — extract snippet and summarise
        snippet = _extract_snippet_for_summary(f)
        if not snippet or snippet.startswith("["):
            # Extraction failed — store a minimal placeholder
            folder_summaries[rel_key] = {
                "summary": f.name,
                "hash":    file_hash,
            }
            continue

        print(f"    Summarising file {idx}/{total}: {f.name}")
        summary = generate_file_summary(f.name, snippet)
        folder_summaries[rel_key] = {
            "summary": summary,
            "hash":    file_hash,
        }
        new_count += 1

    if new_count:
        print(f"  ✓ {new_count} new file summary/summaries generated for {folder_name}")
    else:
        print(f"  ✓ File summaries cached ({len(folder_summaries)} files, unchanged)")

    return folder_summaries


# ── README finder — imported from agents/agent_base.py ───────────────────────
# _find_readme() is now the single canonical copy in agent_base.py.
# This script imports it at module level (see the sys.path setup near line 50).

# ── README stub generator (for new folders with no README) ───────────────────


def generate_readme_stub(folder_name: str, folder: pathlib.Path, description: str) -> pathlib.Path:
    """
    Create a structured README for a new knowledge folder that has none.
    The watcher will append the AUTO-INDEX block later on first run.
    README filename is derived from the folder name — never hardcoded.
    Returns the path to the created README.
    """
    # Collect file names for the stub
    files = [
        f for f in sorted(folder.rglob("*"))
        if f.is_file() and f.suffix.lower() in INCLUDE_EXTS and not should_skip(f)
    ]
    file_list = "\n".join(f"- {f.name}" for f in files[:20])

    # Name README after the folder itself — no fixed suffix
    readme_path = folder / f"{folder_name}.md"
    existing = _find_readme(folder)
    if existing:
        return existing  # don't overwrite existing README

    # Try to generate a richer stub with the LLM
    stub_content = None
    if llm_available():
        prompt = (
            f'I have a knowledge folder called "{folder_name}" with these files:\n\n'
            f"{file_list}\n\n"
            f"Domain description: {description}\n\n"
            f"Write a concise README for this knowledge domain (3-5 paragraphs max). "
            f"Include: what this domain covers, key topics, and how someone would use it. "
            f"Use plain Markdown. No code blocks. No headers beyond # and ##."
        )
        try:
            stub_content = call_llm_generate(prompt)
        except Exception:
            stub_content = None

    if not stub_content:
        stub_content = (
            f"# {folder_name}\n\n"
            f"{description}\n\n"
            f"## Contents\n\n"
            f"{file_list}\n\n"
            f"_Add your own notes about this domain above this line._\n"
        )

    readme_path.write_text(stub_content, encoding="utf-8")
    return readme_path



def generate_sub_agent(domain: dict, agents_dir: pathlib.Path):
    """
    Write agents/agent_<safe>.py for one domain.

    The file is a thin, standalone module that:
      • Imports agent_base.ask() for all shared RAG logic
      • Overrides only what is domain-specific (system_prompt, top_n, max_chars)
      • Can be run directly:  python3 agents/agent_bizops.py "question"

    Domain-specific retrieval hooks are injected here so they live alongside
    the domain definition — not scattered across agent_base.py as global hacks.
    """
    folder_name  = domain["folder_name"]
    safe         = domain["safe_name"]
    agent_name   = domain["agent_name"]
    description  = domain["description"]
    system_prompt = domain.get("system_prompt", (
        f"You are the {agent_name}, a specialist in the {folder_name} knowledge domain.\n"
        f"Domain description: {description}\n"
        f"You answer questions strictly based on the provided document context.\n"
        f"Be concise, accurate, and cite which document your answer came from.\n"
        f"If the answer is not in the provided context, say so clearly — do not guess.\n"
        f"Format your answer in clean markdown."
    ))
    top_n     = domain.get("top_n", 4)
    max_chars = domain.get("max_chars", 6000)

    # ── Domain-specific ask() override (injected per domain) ─────────────────
    # For most domains, the ask() function is a straight pass-through to
    # agent_base.ask().  For domains that need custom retrieval logic (e.g.
    # always pinning certain file types), a domain_ask() override is injected.
    #
    # Convention: if the domain's safe_name matches a known override key, inject
    # extra code; otherwise the override is just a direct call to agent_base.ask().

    # Keys that signal "this domain needs a custom ask override"
    _REVENUE_DOMAINS = {"bizops"}  # extend as needed

    if safe in _REVENUE_DOMAINS:
        domain_ask_body = textwrap.dedent(f"""\
        def domain_ask(question, history, format_instruction=""):
            \"\"\"
            BizOps-specific ask: always pins *Revenue*.xlsx files to the top
            of the context for data/revenue questions so the LLM reads
            authoritative Rev Act @ PC numbers before CRM Won-Deals files.
            \"\"\"
            import json, pathlib, sys
            sys.path.insert(0, str(pathlib.Path(__file__).parent))
            from agent_base import (
                ask as _base_ask, _is_data_question,
                folder_to_safe_name, KB_ROOT, VECTOR_STORE,
                _apply_format_instruction,
            )
            from embeddings import search

            fmt_prompt = _apply_format_instruction(SYSTEM_PROMPT, format_instruction)

            # For non-data questions delegate entirely to base
            if not _is_data_question(question):
                return _base_ask(
                    question=question,
                    folder_name=FOLDER_NAME,
                    agent_name=AGENT_NAME,
                    system_prompt=fmt_prompt,
                    conversation_history=history,
                    top_n=TOP_N,
                    max_chars=MAX_CHARS,
                )

            # Data question: run base search then pin Revenue files to front
            results = search(question, FOLDER_NAME, top_n=TOP_N)
            if results:
                result_paths = {{r["path"] for r in results}}
                safe_name = folder_to_safe_name(FOLDER_NAME)
                idx_path  = VECTOR_STORE / f"{{safe_name}}_index.json"
                if idx_path.exists():
                    try:
                        idx_data = json.loads(idx_path.read_text())
                        for entry in idx_data.get("entries", []):
                            name = entry.get("name", "")
                            if ("revenue" in name.lower()
                                    and name.lower().endswith(".xlsx")
                                    and entry.get("path") not in result_paths):
                                results.append({{
                                    "path":   entry["path"],
                                    "name":   name,
                                    "score":  1.0,
                                    "folder": FOLDER_NAME,
                                }})
                                result_paths.add(entry["path"])
                    except Exception:
                        pass

                def _rev_priority(r):
                    n = r.get("name", "").lower()
                    return 0 if ("revenue" in n and n.endswith(".xlsx")) else 1
                results = sorted(results, key=_rev_priority)

            # Delegate the rest (extraction + LLM call) to base, bypassing its
            # own search by passing the pre-ordered result list via the
            # _pre_ranked_results kwarg (added to agent_base.ask below).
            return _base_ask(
                question=question,
                folder_name=FOLDER_NAME,
                agent_name=AGENT_NAME,
                system_prompt=fmt_prompt,
                conversation_history=history,
                top_n=TOP_N,
                max_chars=MAX_CHARS,
                _pre_ranked_results=results,
            )
        """)
    else:
        domain_ask_body = textwrap.dedent(f"""\
        def domain_ask(question, history, format_instruction=""):
            import sys, pathlib
            sys.path.insert(0, str(pathlib.Path(__file__).parent))
            from agent_base import ask as _base_ask, _apply_format_instruction
            fmt_prompt = _apply_format_instruction(SYSTEM_PROMPT, format_instruction)
            return _base_ask(
                question=question,
                folder_name=FOLDER_NAME,
                agent_name=AGENT_NAME,
                system_prompt=fmt_prompt,
                conversation_history=history,
                top_n=TOP_N,
                max_chars=MAX_CHARS,
            )
        """)

    # Escape the system prompt for embedding in Python source
    sp_escaped = system_prompt.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')

    # Build content at column-0.  Do NOT use textwrap.dedent on a template
    # that is itself indented inside a function — dedent strips the indentation
    # of the template lines, not the interpolated values, causing mismatches.
    lines = [
        "#!/usr/bin/env python3",
        '"""',
        f"agents/agent_{safe}.py — {agent_name}",
        "Auto-generated by scripts/generate.py — do not edit manually.",
        "To regenerate:  python3 scripts/generate.py",
        "",
        f"Domain:  {folder_name}",
        f"Desc:    {description}",
        "",
        "Can be run standalone:",
        f'  python3 agents/agent_{safe}.py "your question"',
        '"""',
        "",
        "import sys",
        "import pathlib",
        "",
        "sys.path.insert(0, str(pathlib.Path(__file__).parent))",
        "",
        "from agent_base import _load_env",
        "_load_env()",
        "",
        f"FOLDER_NAME   = {folder_name!r}",
        f"AGENT_NAME    = {agent_name!r}",
        f'SYSTEM_PROMPT = """{sp_escaped}"""',
        f"TOP_N         = {top_n}",
        f"MAX_CHARS     = {max_chars}",
        "",
        "# ── Domain-specific ask() ─────────────────────────────────────────────────",
        "",
        domain_ask_body,
        "# ── Standalone entry point ────────────────────────────────────────────────",
        "",
        "def main():",
        "    from memory import get_history, add_turn",
        "    import sys as _sys",
        "    if len(_sys.argv) < 2:",
        '        print(f"Usage: python3 {__file__!r} \\"question\\"")',
        "        _sys.exit(1)",
        "    question = _sys.argv[1]",
        "    history  = get_history()",
        "    result   = domain_ask(question, history)",
        '    answer   = result.get("answer", "")',
        "    print(answer)",
        "    add_turn(question, answer)",
        "",
        "",
        'if __name__ == "__main__":',
        "    main()",
        "",
    ]
    content = "\n".join(lines)

    out_path = agents_dir / f"agent_{safe}.py"
    out_path.write_text(content, encoding="utf-8")
    print(f"  ✓ agent_{safe}.py written")
    return out_path


# ── SKILL.md generator ────────────────────────────────────────────────────────

def generate_skill_md(domains: list[dict], agents_dir: pathlib.Path, kb_root: pathlib.Path):
    domain_lines = "\n".join(
        f"- **{d['folder_name']}**: {d['description']}" for d in domains
    )
    folder_names = ", ".join(d["folder_name"] for d in domains)
    trigger_keywords = ", ".join(
        kw for d in domains for kw in d["keywords"][:3]
    )

    # Use SKILL_DIR-relative paths so agents/SKILL.md works on ANY machine
    # after cloning — no absolute paths baked in at generate time.
    # SKILL_DIR is the directory containing SKILL.md (i.e. agents/).
    # The repo root is one level up: $(dirname $SKILL_DIR)
    # agent_knowledgebase.py lives in the same agents/ folder as SKILL.md.
    agent_rel  = "agents/agent_knowledgebase.py"   # relative to repo root
    gen_rel    = "generate.py"                      # root shim, always present

    content = f"""\
---
name: knowledgebase-agent
description: >
  Multi-domain KnowledgeBase agent. Routes questions to the correct
  specialist sub-agent automatically based on your knowledge folders.
  Use when asking about any content in your KnowledgeBase.

  Current domains ({len(domains)}):
{textwrap.indent(domain_lines, "  ")}

  Trigger phrases: ask the agent, KnowledgeBase Agent, query knowledge base,
  {trigger_keywords}, what does my KnowledgeBase say, /kb, /agent

execute: |
  python3 "${{SKILL_DIR}}/../{agent_rel.split('/')[-1]}" "${{QUESTION}}"
---

# KnowledgeBase Agent Skill

## How Bob uses this skill

When you ask Bob a question that triggers this skill, Bob runs:
```
python3 <install-dir>/{agent_rel} "<your question>"
```
The Python script handles **all the AI work locally** (routing, retrieval, answering)
using your local LLM (Ollama / OpenAI / etc.). Bob reads the output and relays it back.

**Bob's Claude is used for:** understanding your request and deciding to invoke this skill.
**Your local LLM is used for:** intent classification, semantic routing, document Q&A.
**No document content is ever sent to Claude.**

## Current Domains
{domain_lines}

## Usage
Just ask naturally — Bob detects the intent and runs the agent:
- "What does my KnowledgeBase say about X?"
- "Ask the KnowledgeBase agent about Y"

## Commands
- `/kb <question>` — query the knowledge base
- `/agent <question>` — same as /kb
- `/kb --clear` — clear conversation memory
- `/kb --memory` — show conversation history summary

## How the pipeline works
```
You → Bob (Claude) → detects skill trigger
                   → runs: python3 {agent_rel} "<question>"
                             ↓
                        keyword_route()  ← fast, no LLM
                             ↓ (if ambiguous)
                        classify_intent() ← your local LLM
                             ↓
                        agent_base.ask() ← README-first RAG pipeline
                             ↓
                        call_llm() or passthrough block
                             ↓
                   → Bob reads stdout and returns answer to you
```

## Setup
To add a new domain: create a folder with documents in your KB root, then run:
```
python3 {gen_rel}
```

## Technical Details
- Embedding: configurable via `KB_EMBED_MODEL` (Ollama / OpenAI / offline fallback)
- LLM: configurable via `KB_MODEL` and `KB_LLM_PROVIDER`
- Conversation memory: persists across sessions (auto-resets after 2h inactivity)
- Invocation: `python3 {agent_rel} "<question>"`
"""

    # Write to agents/SKILL.md (in-repo copy)
    skill_path = agents_dir / "SKILL.md"
    skill_path.write_text(content, encoding="utf-8")

    # Auto-copy to ~/.bob/skills/knowledgebase-agent/SKILL.md if Bob is installed
    bob_skills_dir = pathlib.Path.home() / ".bob" / "skills" / "knowledgebase-agent"
    if bob_skills_dir.parent.parent.exists():  # ~/.bob exists
        bob_skills_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(skill_path, bob_skills_dir / "SKILL.md")
        print(f"  ✓ Skill copied to {bob_skills_dir / 'SKILL.md'}")
    else:
        print(f"  ℹ Bob not detected. To install the skill manually:")
        print(f"    mkdir -p ~/.bob/skills/knowledgebase-agent")
        print(f"    cp agents/SKILL.md ~/.bob/skills/knowledgebase-agent/SKILL.md")


# ── requirements.txt generator ────────────────────────────────────────────────

def generate_requirements(out_path: pathlib.Path):
    # If requirements.txt already exists, never overwrite it.
    # The canonical version is maintained by hand in the repo and includes
    # fastmcp, chromadb, rich, pyyaml, python-docx, and other packages that
    # this minimal stub does not list. Overwriting it strips those entries
    # and breaks tests / installs.
    if out_path.exists():
        return

    content = """\
# KnowledgeBase Agent — Python dependencies
# Install with: pip install -r requirements.txt

# ── Core (required) ───────────────────────────────────────────
fastmcp>=2.0.0        # MCP server framework
httpx>=0.27.0
numpy>=1.26.0
scikit-learn>=1.4.0
watchdog>=4.0.0
rich>=13.0.0          # terminal formatting / progress output
pyyaml>=6.0.0         # YAML config support

# ── Vector store ─────────────────────────────────────────────
chromadb>=0.5.0       # persistent vector index

# ── File format support (required for full document coverage) ─
pypdf>=4.0.0          # PDF reading
python-pptx>=1.0.0    # PPTX/PPT reading
python-docx>=1.1.0    # DOCX reading
openpyxl>=3.1.0       # XLSX/XLS reading

# ── Offline embedding fallback (optional but recommended) ─────
# Install this if you don't have Ollama or an OpenAI API key.
# Downloads ~80MB model on first use (all-MiniLM-L6-v2).
sentence-transformers>=3.0.0

# ── .env file support (optional) ─────────────────────────────
# Already handled natively — no python-dotenv needed.
"""
    out_path.write_text(content, encoding="utf-8")


# ── README.md generator ───────────────────────────────────────────────────────

def generate_readme(domains: list[dict], kb_root: pathlib.Path, out_path: pathlib.Path):
    domain_table_rows = "\n".join(
        f"| `{d['folder_name']}` | {d['description']} |"
        for d in domains
    )
    folder_names = ", ".join(f"`{d['folder_name']}`" for d in domains)

    content = f"""\
# KnowledgeBase Agent

A fully dynamic, multi-domain knowledge base agent system.  
Add a folder of documents → run `scripts/generate.py` → ask questions in natural language.

## Quick Start

```bash
# 1. Clone the repo
git clone <repo-url>
cd KnowledgeBase

# 2. Install dependencies
pip install -r requirements.txt

# 3. Configure your environment (copy and edit)
cp .env.example .env
# Edit .env — set KB_ROOT, KB_MODEL, KB_LLM_PROVIDER etc.

# 4. Add your knowledge folders (any top-level folder with documents)
#    e.g. mkdir "My Project" && cp *.pdf "My Project/"

# 5. Run the generator (discovers folders, builds indexes, generates agents)
python3 scripts/generate.py

# 6. Ask a question
python3 agents/agent_knowledgebase.py "your question here"
```

## Environment Variables

Copy `.env.example` to `.env` and configure:

| Variable | Default | Description |
|---|---|---|
| `KB_ROOT` | _(repo root)_ | Absolute path to your knowledge base directory |
| `KB_LLM_PROVIDER` | `ollama` | LLM provider: `ollama` \\| `openai` \\| `anthropic` \\| `custom` |
| `KB_LLM_BASE_URL` | `http://localhost:11434` | Base URL for the LLM API |
| `KB_MODEL` | `qwen3:14b` | Model name for Q&A and routing |
| `KB_API_KEY` | _(empty)_ | API key for OpenAI / Anthropic / custom providers |
| `KB_EMBED_MODEL` | `nomic-embed-text` | Embedding model (leave blank for offline fallback) |
| `KB_IGNORE_FOLDERS` | _(empty)_ | Comma-separated extra folders to exclude from discovery |

## Current Domains

{domain_table_rows}

## Adding a New Knowledge Domain

1. Create a folder in `{kb_root}` (e.g. `mkdir "Sales Reports"`)
2. Copy your documents into it
3. Run `python3 scripts/generate.py`

That's it. The generator will:
- Auto-discover the new folder
- Build a vector index for it
- Generate a description + keywords using the LLM
- Create `agents/agent_sales_reports.py`
- Update the orchestrator and skill

## Architecture

```
scripts/generate.py            ← run once to set everything up
├── agents/
│   ├── agent_base.py          ← shared RAG logic (extract, embed, ask)
│   ├── embeddings.py          ← dynamic vector index (Ollama/OpenAI/offline)
│   ├── memory.py              ← conversation memory (persists across sessions)
│   ├── agent_knowledgebase.py ← orchestrator (auto-generated)
│   ├── agent_<folder>.py      ← one per domain (auto-generated)
│   ├── SKILL.md               ← Bob skill definition (auto-generated)
│   └── vector_store/
│       ├── <folder>_index.json   ← embeddings cache per domain
│       └── domain_meta.json      ← descriptions + keywords per domain
└── <YourFolder>/              ← your knowledge documents
```

## Supported File Types

`.pdf` `.docx` `.pptx` `.xlsx` `.md` `.txt` `.csv` `.boxnote` `.ppt` `.doc`

## LLM Providers

| Provider | `KB_LLM_PROVIDER` | Notes |
|---|---|---|
| Ollama (local) | `ollama` | Default. Run `ollama serve` first. |
| OpenAI | `openai` | Set `KB_API_KEY` |
| Anthropic | `anthropic` | Set `KB_API_KEY` |
| LM Studio / Jan | `custom` | Set `KB_LLM_BASE_URL` to local server URL |

**No LLM?** Embeddings fall back to `sentence-transformers` (offline, ~80MB).  
Run `scripts/generate.py --no-llm` to skip description/keyword generation.

## Watcher (auto-update on file changes)

```bash
python3 scripts/watch_kb.py
```

Watches for new top-level folders and file changes, then auto-triggers `scripts/generate.py`.

## Bob AI Assistant Integration

If you use [Bob](https://github.com/ibm/bob), the skill is auto-installed to
`~/.bob/skills/knowledgebase-agent/SKILL.md` when you run `scripts/generate.py`.
"""
    out_path.write_text(content, encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate KnowledgeBase agents from discovered folders."
    )
    parser.add_argument("--force",  action="store_true",
                        help="Regenerate everything, ignoring cache")
    parser.add_argument("--no-llm", action="store_true",
                        help="Skip LLM steps (index + file gen only, placeholder descriptions)")
    args = parser.parse_args()

    # ── Step 0: load env ──────────────────────────────────────────────────────
    import time as _time
    _t_start = _time.monotonic()

    load_env(SCRIPT_DIR)
    kb_root    = resolve_kb_root()
    blocklist  = get_blocklist()
    agents_dir = SCRIPT_DIR / "agents"
    agents_dir.mkdir(exist_ok=True)
    (agents_dir / "vector_store").mkdir(exist_ok=True)

    print(f"\n{'='*60}")
    print(f"  KnowledgeBase Agent Generator")
    print(f"  KB_ROOT: {kb_root}")
    print(f"{'='*60}\n")

    # ── Step 1: validate KB_ROOT exists ──────────────────────────────────────
    if not kb_root.exists():
        env_file = SCRIPT_DIR / ".env"
        print(f"✗ KB_ROOT does not exist: {kb_root}")
        if env_file.exists():
            print(f"  Check KB_ROOT in your .env file: {env_file}")
        else:
            print(f"  Set KB_ROOT in a .env file at: {SCRIPT_DIR}/.env")
            print(f"  Example:  KB_ROOT=/path/to/your/documents")
        print(f"  Or run:   python3 scripts/setup.py   to configure the path interactively.")
        sys.exit(1)

    # ── Step 1b: discover folders ─────────────────────────────────────────────
    try:
        folders = discover_folders(kb_root, blocklist)
    except PermissionError as e:
        print(f"✗ Cannot read KB_ROOT: {e}")
        print(f"  Check that you have read access to: {kb_root}")
        sys.exit(1)
    if not folders:
        print(f"✗ No knowledge folders found under {kb_root}")
        print(f"  Create a folder with documents and re-run scripts/generate.py")
        sys.exit(1)
    print(f"Discovered {len(folders)} folder(s): {', '.join(folders)}\n")

    # ── Step 2: clean up stale _index.json files ──────────────────────────────
    # No per-domain .py files are generated; the orchestrator reads domain_meta.json.
    # Delete stale vector index files
    vector_store = agents_dir / "vector_store"
    expected_index_files = {
        f"{folder_to_safe_name(f)}_index.json" for f in folders
    } | {"domain_meta.json", "session_memory.json", "file_summaries.json"}
    for idx_file in vector_store.glob("*_index.json"):
        if idx_file.name not in expected_index_files:
            idx_file.unlink()
            print(f"  🗑  Deleted orphaned index: {idx_file.name}")

    # Clean stale entries from file_summaries.json cache.
    # Keys are stored as POSIX-style paths ("FolderName/file.ext") regardless
    # of OS.  Split on the first "/" to extract the folder name, then check
    # whether that folder is still in our discovered set.
    summaries_path = vector_store / "file_summaries.json"
    if summaries_path.exists():
        try:
            summaries = json.loads(summaries_path.read_text(encoding="utf-8"))
            folder_set = set(folders)
            stale_keys = [
                k for k in summaries
                if k.replace("\\", "/").split("/")[0] not in folder_set
            ]
            if stale_keys:
                for k in stale_keys:
                    del summaries[k]
                summaries_path.write_text(json.dumps(summaries, indent=2), encoding="utf-8")
                print(f"  🗑  Removed {len(stale_keys)} stale summary cache entries")
        except Exception:
            pass

    # ── Step 3: load existing domain_meta ─────────────────────────────────────
    meta_path    = agents_dir / "vector_store" / "domain_meta.json"
    domain_meta: dict[str, dict] = {}
    if meta_path.exists():
        try:
            domain_meta = json.loads(meta_path.read_text())
        except Exception:
            domain_meta = {}

    # ── Step 4 + 5: build indexes + generate meta ─────────────────────────────
    # Import here so env vars are already set
    sys.path.insert(0, str(agents_dir))
    from embeddings import build_index

    use_llm = not args.no_llm
    if use_llm:
        print("Checking LLM availability...", end=" ", flush=True)
        use_llm = llm_available()
        print("✓ available" if use_llm else "✗ not reachable (will use placeholder descriptions)")
        print()

    # Load existing file summaries cache (shared across all domains).
    # This cache persists between runs — the LLM is only called for new or
    # changed files (content-hash based, same pattern as the vector index).
    summaries_path  = agents_dir / "vector_store" / "file_summaries.json"
    summaries_cache: dict[str, dict] = {}
    if summaries_path.exists():
        try:
            summaries_cache = json.loads(summaries_path.read_text(encoding="utf-8"))
        except Exception:
            summaries_cache = {}

    domains_list = []

    for folder_name in folders:
        folder = kb_root / folder_name
        safe   = folder_to_safe_name(folder_name)
        n_files = count_files(folder)

        print(f"[{folder_name}]")

        # Build / update vector index
        print(f"  Building index...")
        build_index(folder_name, force=args.force)

        # Check if we can skip meta generation
        existing = domain_meta.get(folder_name, {})
        cached_count = existing.get("file_count", -1)
        has_meta = bool(existing.get("description") and existing.get("keywords"))

        if has_meta and cached_count == n_files and not args.force:
            print(f"  ✓ Meta cached ({n_files} files, unchanged)")
            entry = existing
        elif use_llm:
            print(f"  Generating description + keywords via LLM...")
            try:
                meta = generate_domain_meta(folder_name, folder)
                description = meta["description"]
                keywords    = meta["keywords"]
                print(f"  ✓ Description: {description[:80]}...")
            except Exception as e:
                print(f"  ⚠ LLM meta failed ({e}) — using placeholder")
                description = f"Knowledge domain: {folder_name}"
                keywords    = [folder_name.lower(), safe.replace("_", " ")]
            agent_name    = f"{folder_name} Agent"
            system_prompt = (
                f"You are the {agent_name}, a specialist in the {folder_name} knowledge domain.\n"
                f"Domain description: {description}\n"
                f"You answer questions strictly based on the provided document context.\n"
                f"Be concise, accurate, and cite which document your answer came from.\n"
                f"If the answer is not in the provided context, say so clearly — do not guess.\n"
                f"Format your answer in clean markdown."
            )
            entry = {
                "folder_name":  folder_name,
                "safe_name":    safe,
                "agent_name":   agent_name,
                "description":  description,
                "keywords":     keywords,
                "file_count":   n_files,
                "top_n":        existing.get("top_n", 4),
                "max_chars":    existing.get("max_chars", 6000),
                "system_prompt": system_prompt,
            }
        else:
            print(f"  ℹ Using placeholder description (re-run without --no-llm to generate)")
            agent_name    = f"{folder_name} Agent"
            description   = existing.get("description") or f"Knowledge domain: {folder_name}"
            keywords      = existing.get("keywords") or [folder_name.lower(), safe.replace("_", " ")]
            system_prompt = existing.get("system_prompt") or (
                f"You are the {agent_name}, a specialist in the {folder_name} knowledge domain.\n"
                f"Domain description: {description}\n"
                f"You answer questions strictly based on the provided document context.\n"
                f"Be concise, accurate, and cite which document your answer came from.\n"
                f"If the answer is not in the provided context, say so clearly — do not guess.\n"
                f"Format your answer in clean markdown."
            )
            entry = {
                "folder_name":  folder_name,
                "safe_name":    safe,
                "agent_name":   agent_name,
                "description":  description,
                "keywords":     keywords,
                "file_count":   n_files,
                "top_n":        existing.get("top_n", 4),
                "max_chars":    existing.get("max_chars", 6000),
                "system_prompt": system_prompt,
            }

        # ── Per-file summaries ────────────────────────────────────────────────
        # Generate (or load from cache) a 3–5 sentence LLM summary for every
        # file in this domain.  Summaries are stored in two places:
        #   1. agents/vector_store/file_summaries.json  — persistent hash cache
        #   2. entry["file_summaries"]                  — inline in domain_meta
        #      (flat dict: { "FolderName/file.ext": "summary text", ... })
        #
        # The inline copy lets classify_intent() use per-file context for
        # routing without reading a second file at query time.
        if use_llm:
            print(f"  Generating file summaries...")
            folder_summaries = build_file_summaries(
                folder_name    = folder_name,
                folder         = folder,
                kb_root        = kb_root,
                existing_cache = summaries_cache,
                force          = args.force,
            )
            # Merge back into the shared cache (written once after the loop)
            summaries_cache.update(folder_summaries)
            # Inline in domain_meta: flat map of path → summary string
            entry["file_summaries"] = {
                k: v["summary"] for k, v in folder_summaries.items()
            }
        else:
            # --no-llm: carry forward whatever was already stored
            entry["file_summaries"] = existing.get("file_summaries", {})

        domain_meta[folder_name] = entry
        domains_list.append(entry)

        # Generate (or regenerate) per-domain agent file
        generate_sub_agent(entry, agents_dir)

        # Create README stub for folders that don't have one yet
        folder_path = kb_root / folder_name
        if not _find_readme(folder_path):
            stub = generate_readme_stub(folder_name, folder_path, entry["description"])
            print(f"  ✓ README stub created: {stub.name}")

        print()

    # Remove stale entries from domain_meta:
    #   a) folders that were deleted (no longer in discovered set)
    #   b) folders whose names would now be excluded by is_ignored()
    #      (e.g. *.egg-info entries left over from before fix 1.1)
    for key in list(domain_meta.keys()):
        name_lower = key.lower()
        if key not in folders or name_lower.endswith(".egg-info") or name_lower.endswith(".dist-info"):
            del domain_meta[key]
            print(f"  🗑  Removed stale domain: {key}")

    # ── Step 5b: write file_summaries.json cache ──────────────────────────────
    if use_llm:
        summaries_path.write_text(
            json.dumps(summaries_cache, indent=2), encoding="utf-8"
        )
        total_summaries = sum(
            1 for v in summaries_cache.values() if v.get("summary")
        )
        print(f"✓ file_summaries.json written ({total_summaries} file summaries)\n")

    # ── Step 6: write domain_meta.json ────────────────────────────────────────
    meta_path.write_text(json.dumps(domain_meta, indent=2), encoding="utf-8")
    print(f"✓ domain_meta.json written ({len(domain_meta)} domains)\n")

    # ── Step 7: orchestrator reads domain_meta.json — nothing more to generate ─
    print("  ✓ Orchestrator ready (data-driven from domain_meta.json)\n")

    # ── Step 8: generate requirements.txt ────────────────────────────────────
    req_path = SCRIPT_DIR / "requirements.txt"
    existed  = req_path.exists()
    generate_requirements(req_path)
    print(f"✓ requirements.txt {'preserved (already exists)' if existed else 'written'}\n")

    # ── Step 9: generate SKILL.md ─────────────────────────────────────────────
    # NOTE: README.md is intentionally NOT regenerated here.
    # It is a hand-authored installation guide — overwriting it would destroy
    # the ⚡ AI Agent Installation Guide section and all setup instructions.
    # Per-domain README stubs are created above (inside the folder loop) when
    # a domain folder has no README yet.  The repo-level README.md is never
    # touched by generate.py.
    # ── Step 9: generate SKILL.md ────────────────────────────────────────────
    print("Generating SKILL.md...")
    generate_skill_md(domains_list, agents_dir, kb_root)
    print()

    # ── Done ──────────────────────────────────────────────────────────────────
    elapsed = _time.monotonic() - _t_start
    mins, secs = divmod(int(elapsed), 60)
    elapsed_str = f"{mins}m {secs}s" if mins else f"{secs}s"

    # Write audit entry so drift-check can compare against live folder state.
    try:
        audit_path = kb_root / ".kb_index" / "audit.jsonl"
        audit_path.parent.mkdir(parents=True, exist_ok=True)
        total_files = sum(d.get("file_count", 0) for d in domains_list)
        entry = {
            "ts":      datetime.datetime.now().isoformat(timespec="seconds"),
            "event":   "generate_complete",
            "reason":  "manual" if not os.environ.get("KB_WATCHER_RUN") else "watcher",
            "domains": [d["folder_name"] for d in domains_list],
            "files":   total_files,
        }
        with audit_path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry) + "\n")
    except Exception:
        pass  # audit failure never blocks the main run

    print(f"{'='*60}")
    print(f"  ✓ Done in {elapsed_str}")
    print(f"  {len(domains_list)} domain(s): {', '.join(d['folder_name'] for d in domains_list)}")
    print(f"\n  Test it:")
    print(f'    python3 agents/agent_knowledgebase.py "your question"')
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
