#!/usr/bin/env python3
"""
agent_cp4i_docs.py — CP4I Docs Agent
-------------------------------------
Auto-generated by generate.py. Re-run generate.py to update.

Domain      : CP4I Docs
Description : Folder containing Cloud Pak for Integration documentation, presentations, and sales materials.
Agent file  : agents/agent_cp4i_docs.py

Usage (standalone):
  python3 agents/agent_cp4i_docs.py "your question"

Usage (called by orchestrator):
  from agents.agent_cp4i_docs import ask
  result = ask("your question")
"""

import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from agent_base import ask as _base_ask

# ── Domain config ─────────────────────────────────────────────────────────────

AGENT_NAME   = "CP4I Docs Agent"
AGENT_FOLDER = "CP4I Docs"
TOP_N_FILES  = 4
MAX_CHARS    = 6000

SYSTEM_PROMPT = """You are the CP4I Docs Agent, a specialist in the CP4I Docs knowledge domain.
Domain description: Folder containing Cloud Pak for Integration documentation, presentations, and sales materials.
You answer questions strictly based on the provided document context.
Be concise, accurate, and cite which document your answer came from.
If the answer is not in the provided context, say so clearly — do not guess.
Format your answer in clean markdown."""


# ── Public interface ──────────────────────────────────────────────────────────

def ask(question: str, conversation_history: list[dict] | None = None) -> dict:
    """
    Answer a question using CP4I Docs.

    Returns:
        { "agent", "answer", "sources", "found" }
    """
    return _base_ask(
        question             = question,
        folder_name          = AGENT_FOLDER,
        agent_name           = AGENT_NAME,
        system_prompt        = SYSTEM_PROMPT,
        conversation_history = conversation_history,
        top_n                = TOP_N_FILES,
        max_chars            = MAX_CHARS,
    )


# ── Standalone entry point ────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f'Usage: python3 agents/agent_cp4i_docs.py "your question"')
        sys.exit(1)

    question = " ".join(sys.argv[1:])
    print(f"\n" + "=" * 60)
    print(f"  {AGENT_NAME}")
    print("=" * 60)
    print(f"  Question: {question}")
    print(f"  Searching {AGENT_FOLDER}...\n")

    result = ask(question)

    print(f"  Sources used ({len(result['sources'])}): ")
    for s in result["sources"]:
        print(f"    [{s['score']:.3f}] {s['name']}")

    print("\n" + "─" * 60)
    print(result["answer"])
    print("─" * 60 + "\n")
